#!/usr/bin/env python3
"""Generate proximity-band dataset configs for the proximity-stratified relearning sweep.

Writes one QADataset YAML per attack arm under
configs/data/datasets/{topic}/bands/. Each band keeps a subset of the SUITE
retain (or forget) rows via `exclude_label_prefixes` — QADataset only supports
exclusion, so every config lists all prefixes OUTSIDE the band. Trailing
hyphens ("Semantic-1-") prevent prefix collisions ("Semantic-10-", "K10-").

Band → data map (see docs/PROXIMITY_EXPERIMENT.md):
  R0..R5   semantic tiers from retain_train (the tier train halves)
  R6, R7   semantic tiers s11..s14 — these exist ONLY in retain_eval
  C_gk     general-knowledge rows only ("distance ≈ ∞" drift anchor)
  C_lex    lexical rows only (token overlap without semantic overlap)
  A_forget_partial  5 of 25 forget facts (recovery is judged on the other 20)
  A_forget_full     all forget facts (absolute ceiling)
  (C_full needs no config — it is the stock {topic}/retain.yaml)

Run `python scripts/verify_band_configs.py` after regenerating.
"""

import argparse
from pathlib import Path

SEMANTIC_TRAIN_TIERS = list(range(0, 11))   # tiers present in retain_train
SEMANTIC_ALL_TIERS = list(range(0, 16))     # tiers present in retain_eval
GROUP_PREFIXES = ["GK-", "Lexical-", "Syntax-"]
FORGET_FACTS = [f"K{i}" for i in range(1, 21)] + [f"M{i}" for i in range(1, 6)]
PARTIAL_KEEP = ["K1", "K2", "K3", "K4", "K5"]

# band name -> (split, kept semantic tiers | None)
SEMANTIC_BANDS = {
    "R0": ("retain_train", [0]),
    "R1": ("retain_train", [1, 2]),
    "R2": ("retain_train", [3, 4]),
    "R3": ("retain_train", [5, 6]),
    "R4": ("retain_train", [7, 8]),
    "R5": ("retain_train", [9, 10]),
    # s11..s15 exist only in retain_eval (never seen during unlearning).
    # R7 uses s13+s14; s15 is left out (50 rows already; see docs).
    "R6": ("retain_eval", [11, 12]),
    "R7": ("retain_eval", [13, 14]),
}


def semantic_excludes(split: str, keep: list) -> list:
    tiers = SEMANTIC_ALL_TIERS if split == "retain_eval" else SEMANTIC_TRAIN_TIERS
    ex = [f"Semantic-{t}-" for t in tiers if t not in keep]
    return GROUP_PREFIXES + ex


def control_excludes(keep_group: str) -> list:
    # "Semantic-" alone covers every tier.
    groups = {"GK-", "Lexical-", "Syntax-", "Semantic-"}
    groups.discard(keep_group)
    return sorted(groups)


def forget_excludes(keep_facts: list) -> list:
    return [f"{f}-" for f in FORGET_FACTS if f not in keep_facts]


def render(key: str, split: str, topic: str, excludes: list, forget_data: bool,
           comment: str) -> str:
    ex_yaml = " []" if not excludes else (
        "\n" + "\n".join(f"      - \"{p}\"" for p in excludes))
    # Retain-based arms mirror {topic}/retain.yaml exactly (incl. the
    # add_refusal_context flag) so the ONLY difference vs the stock relearn
    # attack is which rows are included. NOTE: src/train.py force-disables
    # refusal context for all non-JensUn++ trainers (GradLearn included), so
    # at runtime every relearn arm — C_full and bands alike — uses the plain
    # context pool; the flag here only preserves config parity. Forget-based
    # arms (A_*) set it false explicitly: the attacker fine-tunes on true
    # (question, answer) pairs.
    if forget_data:
        context_block = (
            "    add_context: true\n"
            "    add_refusal_context: false\n")
    else:
        context_block = (
            "    add_context: true\n"
            "    add_refusal_context: true\n"
            f"    forget_direct_path: \"configs/data/datasets/{topic}/forget_direct.json\"\n")
    return f"""# {comment}
# Auto-generated by scripts/gen_band_configs.py — edit that script, not this file.
{key}:
  handler: QADataset
  args:
    hf_args:
      name: "default"
      split: "{split}"
      path: "apeleg/SUITE"
    filter_topic: "{topic}"
    question_key: "question"
    answer_key: "answer"
    max_length: 512
{context_block}    exclude_label_prefixes:{ex_yaml}
    skip_first_n_rows: 0
    max_rows: 0
    skip_range_start: -1
    skip_range_end: -1
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--topic", default="challenger_disaster")
    args = ap.parse_args()
    topic = args.topic

    root = Path(__file__).resolve().parents[1]
    out_dir = root / "configs" / "data" / "datasets" / topic / "bands"
    out_dir.mkdir(parents=True, exist_ok=True)

    configs = {}
    for band, (split, keep) in SEMANTIC_BANDS.items():
        tiers = "+".join(f"s{t}" for t in keep)
        configs[band] = render(
            f"{topic}_band_{band}", split, topic,
            semantic_excludes(split, keep), forget_data=False,
            comment=f"Proximity band {band}: semantic tiers {tiers} ({split}).")
    configs["C_gk"] = render(
        f"{topic}_band_C_gk", "retain_train", topic,
        control_excludes("GK-"), forget_data=False,
        comment="Control C-GK: general-knowledge rows only (drift anchor).")
    configs["C_lex"] = render(
        f"{topic}_band_C_lex", "retain_train", topic,
        control_excludes("Lexical-"), forget_data=False,
        comment="Control C-Lex: lexical rows only (token overlap, no semantic overlap).")
    configs["A_forget_partial"] = render(
        f"{topic}_band_A_forget_partial", "forget_train", topic,
        forget_excludes(PARTIAL_KEEP), forget_data=True,
        comment=f"Ceiling A-Forget-partial: facts {'+'.join(PARTIAL_KEEP)} only; "
                "recovery is read out on the 20 held-out facts.")
    configs["A_forget_full"] = render(
        f"{topic}_band_A_forget_full", "forget_train", topic,
        [], forget_data=True,
        comment="Ceiling A-Forget-full: the entire forget training set.")

    for band, text in configs.items():
        path = out_dir / f"{band}.yaml"
        path.write_text(text, newline="\n", encoding="utf-8")
        print(f"wrote {path.relative_to(root)}")


if __name__ == "__main__":
    main()
